### PR TITLE
Fix hiding lists and other types in slides.typ

### PR DESCRIPTION
**Pull request by PgBiel**
Hello again, and thanks once more for the project! Just wanted to submit this patch as well: it seems that lists, equations and possibly other types aren't properly hidden when using `multislide` - lists leave their bullets behind when hidden; equations just straight up appear throughout all slides (even those where they are supposed to be hidden); etc. This is due to limitations in the standard `hide()` function.

I managed, however, to easily solve this issue by wrapping them in a `box()`. I also created a function for this, `default_box()`, which wraps them in a box while **ensuring that the box's default attributes are kept intact** (i.e., make the code immune to possible conflicts with `#set box`). (This should be fine, since the usage of `box()` here is an implementation detail, simply a workaround to make `hide()` work with any type, while preserving the document structure.)

Hope this is helpful, and thanks again!

### CODE REVIEW

**Comment by PgBiel** [comment]
Update: This seems to cause some layout/positioning issues with multi-line hidden blocks. Will mark as draft while I try to figure this out

**Comment by andreasKroepelin** [comment]
Interesting... I kinda like that all bullet points/enum numbers are always visible, it gives some kind of outline. Although I admit that that is not the behaviour I intended. That it doesn't hide equations at all is a real issue though, of course. So good idea using the `#box`! Although it makes sense that this doesn't work with multiline content. Could we just use `#block` then instead?

**Comment by PgBiel** [comment]
Hello @andreasKroepelin, thanks for the input! I've done some local testing, and I believe a good approach might be wrapping everything in a box (including the output content, for consistency), and having those boxes forcibly have a width of 100%. This not only fixes multiline issues (and also issues when using, for e.g., `align(right)`), but also allows this effect (of 100% width, which might be undesirable) to be cancelled by wrapping the given text in boxes (i.e., instead of specifying `#multislide(...)[a][b][c]`, which would print a, b, c in separate lines, you would be able to specify `#multislide[#box[a]][#box[b]][#box[c]]`, which'd print them like "abc"), which gives more power to the user, I believe.

(I believe the usage of boxes does have some impact in spacing, but, from my tests, it seems to be very minor, or imperceptible.)

It seems that using `#block` also worked in general, and it looked really promising, but sadly it added way too much (irreversible) spacing around things, which will probably be undesirable most of the time. I believe this approach (of using 100% width boxes) is more flexible.

Note that, upon debugging, the reason this PR caused issues with multi-line boxes was because `width: auto` never assumed a width of 100%, even when it was reasonable to do so (e.g. centered equation or `#align(right)`). Using `width: 100%` fixes those issues by providing a reasonable default,  while also allowing users to "turn that off" or control the width of the boxes by simply wrapping their content in inner boxes.

Also, maybe we could add some parameter to customize everything about this (e.g. maybe the user wants things to actually be wrapped in `block`s). Maybe we could take some sort of callback function that defaults to wrapping in a box? I don't know. Although, this does in general seem like a reasonable default behavior. Tell me what you think!

**Comment by PgBiel** [comment]
Well, I'm satisfied with the result now (see a demo at https://typst.app/project/rmzz4JuXHkpjw8NEMXxJEf), so I'm gonna mark the PR as ready. But feel free to share any more feedback you might have!

**Comment by PgBiel** [comment]
Also, there is a small caveat: by wrapping the contents, enum counters get reset for each block. That is, writing `#(tools.one-by-one)[+ a][+ b][+ c]` will produce something like `1. a`, `1. b` and `1. c`. However, this can be bypassed by simply writing the numbers directly (`#(tools.one-by-one)[1. a][2. b][3. c]`), which also considers custom numbering defined outside, so it should be fine.

**Comment by PgBiel** [comment]
Regarding the caveat above, I've also tried keeping the output body intact (thus preserving enumeration counters) while preserving the height of the hidden block (and thus enabling consistency in an alternative way) by calculating the body's height on every slide, and using that as the fixed height of the output block.

However, it does produce some weird output, as, for example, adding more list items seemed to cause an equation to not center anymore from one slide to another (which is really weird).
Additionally, adding any `#box[]` inside one of the hidden content blocks seemed to cause a resource leak (memory leak + huge CPU usage) and a crash on the compiler, which is, uh... really weird (I'll probably report this bug to them, lol).

So, in the end, maybe the above approach is better, as it is guaranteed to be consistent, while "procedurally generating" the body as is can cause many issues.

The modifications that I describe at the beginning of this comment are listed below.

```typst
let conditional-display(i) = {
    (subslides, body) => if subslides.contains(i) {
        (body)  // keep body intact, so as to preserve enumeration counters
    } else {
        if mode == "hide" {
            hide(full_box(body))
        } else {
            text(gray.lighten(50%), full_box(body))
        }
    }
}

// --snip--

let one-by-one(start: 1, ..children) = {
    let body = {
      for child in children {
        child
      }
    }
    let hidden_body = {
      for idx, child in children.pos() {
        beginning(start + idx, child)
      }
    }
    // calculate the expected height
    // this seems to cause a memleak and crash when children contain #box[]es
    style(styles => block(hidden_body, height: measure(body, styles).height))
}
```

**Comment by andreasKroepelin** [comment]
Thank you so much for your investigation! Given what you found, I think we should settle with the PR as it is. I will try this out and see if I like how it looks for myself. Afterwards, I will merge another idea I had (see the `simplify-api` branch), which unfortunately introduces conflicts with your PR. But I should be able to merge it anyway so that you are credited in the git log.

Looking forward to further contributions from you!

**Comment by PgBiel** [comment]
Great job @andreasKroepelin, the API is indeed much simpler to use now! I really do like the combined result of our efforts. This library has great potential! Thanks again for all the cooperation, and for the library!

**Pull request merged**
